INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('1', 'China', 'Beschreibung Blog 1', 'https://ki-lian.ch/in307blog_images/china.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('2', 'Spanien', 'Beschreibung Blog 2', 'https://ki-lian.ch/in307blog_images/spanien.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('3', 'Frankreich', 'Beschreibung Blog 3', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('4', 'Schweiz', 'Beschreibung Blog 4', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('5', 'Namaste India', 'Beschreibung Blog 5', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('6', 'Honey Hunting in Bangladesch', 'Beschreibung Blog 6', 'https://ki-lian.ch/in307blog_images/bangladesch.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('7', 'Hongkong', 'Beschreibung Blog 7', 'https://ki-lian.ch/in307blog_images/hongkong.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('8', 'Vatikan', 'Beschreibung Blog 8', 'https://ki-lian.ch/in307blog_images/vatikan.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('9', 'Italien', 'Beschreibung Blog 9', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('10', 'Valkane in Island', 'Beschreibung Blog 10', 'https://ki-lian.ch/in307blog_images/island.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('11', 'Gleitschirmfliegen ins Bosinien und Herzegowina', 'Beschreibung Blog 11', 'https://ki-lian.ch/in307blog_images/bosnien_und_herzegowina.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('12', 'Laos', 'Beschreibung Blog 12', 'https://ki-lian.ch/in307blog_images/laos.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('13', 'Myanmar Bagan', 'Beschreibung Blog 13', 'https://ki-lian.ch/in307blog_images/myanmar.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('14', 'Holland', 'Beschreibung Blog 14', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('15', 'Deutschland', 'Beschreibung Blog 15', 'https://ki-lian.ch/in307blog_images/deutschland.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('16', 'Trekking Nepal', 'Beschreibung Blog 16', 'https://ki-lian.ch/in307blog_images/nepal.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('17', 'UAE', 'Beschreibung Blog 17', 'https://ki-lian.ch/in307blog_images/uae.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('18', 'Österrich', 'Beschreibung Blog 18', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('19', 'Lichtenstein', 'Beschreibung Blog 19', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('20', 'Thailand', 'Beschreibung Blog 20', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('21', 'Polen', 'Beschreibung Blog 21', 'https://ki-lian.ch/in307blog_images/fuer_den_fuchs.jpg');
