INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('1', 'Thalamkang Guest House ', 'China Blog', 'https://ki-lian.ch/in307blog_images/tiny/china.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('2', 'Spanien', 'Beschreibung Blog 2', 'https://ki-lian.ch/in307blog_images/tiny/spanien.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('3', 'Frankreich', 'Beschreibung Blog 3', 'https://ki-lian.ch/in307blog_images/tiny/frankreich.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('4', 'Schweiz', 'Beschreibung Blog 4', 'https://ki-lian.ch/in307blog_images/tiny/schweiz.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('5', 'Namaste', 'Beschreibung Blog 5', 'https://ki-lian.ch/in307blog_images/tiny/indien.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('6', 'Honey Hunting', 'Bangladesch Blog', 'https://ki-lian.ch/in307blog_images/tiny/bangladesch.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('7', 'Localview', 'Hongkong Blog', 'https://ki-lian.ch/in307blog_images/tiny/hongkong.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('8', 'Im kleinsten Land der Welt', 'Vatikan Blog', 'https://ki-lian.ch/in307blog_images/tiny/vatikan.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('9', 'Ubuntu Cola', 'Italien Blog', 'https://ki-lian.ch/in307blog_images/tiny/italien.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('10', 'Im Land der Seen, Flüsse und Vulkane', 'Island Blog', 'https://ki-lian.ch/in307blog_images/tiny/island.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('11', 'Gleitschirmfliegen im Ausland', 'Bosnien und Herzegowina unsicher machen', 'https://ki-lian.ch/in307blog_images/tiny/bosnien_und_herzegowina.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('12', 'Mönche', 'Laos Blog', 'https://ki-lian.ch/in307blog_images/tiny/laos.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('13', 'Bagan besuchen', 'Myanmar Blog', 'https://ki-lian.ch/in307blog_images/myanmar.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('14', 'Zu viel zum Essen', 'Holland Ess-Blog', 'https://ki-lian.ch/in307blog_images/tiny/holland.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('15', 'Schachtürke', 'Diebold Nixdorf Museum Deutschland Blog', 'https://ki-lian.ch/in307blog_images/tiny/deutschland.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('16', 'Trekking Kanchenjunga', 'Nepal Blog', 'https://ki-lian.ch/in307blog_images/tiny/nepal.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('17', 'Burj Khalifa', 'UAE Blog', 'https://ki-lian.ch/in307blog_images/tiny/uae.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('18', 'Prater Wien', 'Österreich Blog', 'https://ki-lian.ch/in307blog_images/tiny/oesterreich.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('19', 'Lichtenstein', 'Beschreibung Blog', 'https://ki-lian.ch/in307blog_images/tiny/fuer_den_fuchs.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('20', 'Bangkog Apartment', 'Thailand Blog', 'https://ki-lian.ch/in307blog_images/tiny/thailand.jpg');
INSERT INTO `blog` (`id`, `title`, `description`, `image`) VALUES ('21', 'Tischtennis', 'Tischtennis Traininsslager in Danzig Polen', 'https://ki-lian.ch/in307blog_images/tiny/fuer_den_fuchs.jpg');
