version: "3"
services:
  database:
    container_name: blog_mysql_container
    image: mysql:8.0.34
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "travel"
      MYSQL_DATABASE: "db_blog"
      MYSQL_USER: "blog"
      MYSQL_PASSWORD: "blog"
      DB_PORT: "3306"
      APP_PORT: "3000"
      DB_HOST: "localhost"
    ports:
      - "3306:3306"
    networks:
      blog_backend:
  phpmyadmin:
    container_name: blog_phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: blog_mysql_container
    depends_on:
      - database
    ports:
      - "8080:80"
    networks:
      blog_backend:
networks:
  blog_backend: