include:
  - docker-compose.backend.yml

version: "3"
services:
  blog_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "docker.pkg.github.com/nailik2018/in307blog_backend/nestjs:latest"
    container_name: blog_backend
    ports:
      - "3000:3000"
    networks:
      - blog_backend
    command: npm run start:dev
    env_file:
      - .env